"""
Alert Entity - System alerts and notifications

Represents alerts generated by the system (predictive, ESG, operational).
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict
from uuid import UUID, uuid4
from enum import Enum


class AlertLevel(str, Enum):
    """Alert severity levels"""
    INFO = "info"  # Level 0: Informational
    WARNING = "warning"  # Level 1: Warning
    CRITICAL = "critical"  # Level 2: Critical
    EMERGENCY = "emergency"  # Level 3: Emergency


class AlertStatus(str, Enum):
    """Alert lifecycle status"""
    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    CLOSED = "closed"


class AlertCategory(str, Enum):
    """Alert categories"""
    PREDICTIVE = "predictive"  # Machine failure prediction
    ESG = "esg"  # ESG/emissions threshold
    ENERGY = "energy"  # Energy consumption anomaly
    WATER = "water"  # Water usage anomaly
    OPERATIONAL = "operational"  # Operational parameter out of range
    SAFETY = "safety"  # Safety-related


@dataclass
class Alert:
    """
    Alert entity

    Represents an alert generated by the system.
    Alerts are triggered by threshold violations, predictions, or anomalies.
    """
    id: UUID
    tenant_id: UUID
    site_id: UUID
    machine_id: UUID
    category: AlertCategory
    level: AlertLevel
    status: AlertStatus
    title: str
    description: str
    triggered_at: datetime
    acknowledged_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None
    resolved_by: Optional[str] = None
    resolution_notes: Optional[str] = None
    metadata: Dict[str, any] = field(default_factory=dict)

    @staticmethod
    def create(
        tenant_id: UUID,
        site_id: UUID,
        machine_id: UUID,
        category: AlertCategory,
        level: AlertLevel,
        title: str,
        description: str,
        metadata: Optional[Dict[str, any]] = None
    ) -> "Alert":
        """Factory method to create a new alert"""
        return Alert(
            id=uuid4(),
            tenant_id=tenant_id,
            site_id=site_id,
            machine_id=machine_id,
            category=category,
            level=level,
            status=AlertStatus.OPEN,
            title=title,
            description=description,
            triggered_at=datetime.utcnow(),
            metadata=metadata or {}
        )

    def acknowledge(self, user: str) -> None:
        """Acknowledge the alert"""
        if self.status == AlertStatus.OPEN:
            self.status = AlertStatus.ACKNOWLEDGED
            self.acknowledged_at = datetime.utcnow()
            self.acknowledged_by = user

    def start_investigation(self) -> None:
        """Mark alert as being investigated"""
        if self.status in [AlertStatus.OPEN, AlertStatus.ACKNOWLEDGED]:
            self.status = AlertStatus.INVESTIGATING

    def resolve(self, user: str, notes: Optional[str] = None) -> None:
        """Resolve the alert"""
        self.status = AlertStatus.RESOLVED
        self.resolved_at = datetime.utcnow()
        self.resolved_by = user
        self.resolution_notes = notes

    def close(self) -> None:
        """Close the alert"""
        if self.status == AlertStatus.RESOLVED:
            self.status = AlertStatus.CLOSED
